package com.innova.analyzer.data.models

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * THE CONTRACT: This represents a single network connection or packet intercept.
 * It doubles as our Room Database table to save hackathon development time.
 */
@Entity(tableName = "network_events")
data class NetworkEvent(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L, // Auto-generated by Room DB

    // 1. Time & Identity
    val timestamp: Long, // Use System.currentTimeMillis()
    val uid: Int, // The Android User ID (from ConnectivityManager)
    val packageName: String?, // e.g., "com.android.chrome" (Crucial for fetching App Icons in the UI)
    val appName: String?, // e.g., "Google Chrome"

    // 2. Network Layer
    val protocol: ConnectionProtocol,
    val sourceIp: String,
    val sourcePort: Int,
    val destIp: String,
    val destPort: Int,

    // 3. Application Layer (The Magic)
    val domain: String?, // The extracted TLS SNI (e.g., "api.tracker.com"). Null if HTTP/Unknown.
    val payloadSize: Int, // Size in bytes. Used for the "Top Data Consuming Apps" chart.

    // 4. Threat Analytics
    val isSuspicious: Boolean = false // Set to true if Phase 3 Trie matches the domain
)

/**
 * Enum for clean UI state management and database storage.
 * Makes it easy to color-code protocols in the Jetpack Compose Dashboard.
 */
enum class ConnectionProtocol {
    TCP,
    UDP,
    DNS,
    HTTP, // Optional: if you specifically parse port 80
    HTTPS, // Optional: if you specifically parse port 443 with SNI
    UNKNOWN
}